// ═══════════════════════════════════════════════════════════════════════
// exerciseSeedData.js — Initial Exercise Library (30+ exercises)
// ═══════════════════════════════════════════════════════════════════════
// This file contains all the seed data for the exercise database.
// Each exercise has complete information: instructions, tips,
// common mistakes, benefits, and workout defaults.
//
// Run "npm run seed" from the backend folder to populate the database.
// ═══════════════════════════════════════════════════════════════════════

const exercises = [

  // ═══════════════════════════════════════════════════════════════════
  // CHEST EXERCISES
  // ═══════════════════════════════════════════════════════════════════

  {
    name: 'Push-Up',
    slug: 'push-up',
    description: 'A classic bodyweight exercise that builds chest, shoulder, and tricep strength using your own body weight.',
    category: 'Chest',
    muscleGroups: ['Chest', 'Shoulders', 'Triceps', 'Core'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Strength',
    instructions: [
      'Start in a high plank position with hands shoulder-width apart.',
      'Keep your body in a straight line from head to heels.',
      'Lower your chest towards the floor by bending your elbows.',
      'Push back up to the starting position.',
      'Repeat for the desired number of reps.',
    ],
    tips: [
      'Keep your core tight throughout the movement.',
      'Do not let your hips sag or pike up.',
      'Breathe in on the way down, out on the way up.',
    ],
    mistakes: [
      'Flaring elbows too wide — keep them at 45 degrees.',
      'Letting hips sag towards the ground.',
      'Not going low enough — chest should nearly touch the floor.',
    ],
    benefits: [
      'Builds upper body pushing strength.',
      'No equipment needed — do anywhere.',
      'Engages core for stability.',
    ],
    contraindications: [
      'Wrist injuries or carpal tunnel.',
      'Shoulder impingement.',
    ],
    image: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400',
    video: '',
    caloriesPerMinute: 7,
    defaultSets: 3,
    defaultReps: 15,
    defaultDuration: 0,
    restTime: 60,
  },

  {
    name: 'Bench Press',
    slug: 'bench-press',
    description: 'The king of chest exercises. Uses a barbell to build massive chest, shoulder, and tricep strength.',
    category: 'Chest',
    muscleGroups: ['Chest', 'Shoulders', 'Triceps'],
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    instructions: [
      'Lie flat on a bench with your eyes under the bar.',
      'Grip the bar slightly wider than shoulder-width.',
      'Unrack the bar and hold it above your chest with arms straight.',
      'Lower the bar to your mid-chest slowly.',
      'Press the bar back up to the starting position.',
    ],
    tips: [
      'Plant your feet firmly on the floor.',
      'Squeeze your shoulder blades together.',
      'Use a spotter for heavy lifts.',
    ],
    mistakes: [
      'Bouncing the bar off the chest.',
      'Lifting hips off the bench.',
      'Gripping too wide or too narrow.',
    ],
    benefits: [
      'Builds maximum chest strength and size.',
      'Compound movement — works multiple muscles.',
      'Easy to progressively overload with more weight.',
    ],
    contraindications: [
      'Shoulder injuries or rotator cuff problems.',
      'Recent chest surgery.',
    ],
    image: 'https://images.unsplash.com/photo-1534368959876-26bf04f2c947?w=400',
    video: '',
    caloriesPerMinute: 8,
    defaultSets: 4,
    defaultReps: 10,
    defaultDuration: 0,
    restTime: 90,
  },

  {
    name: 'Dumbbell Fly',
    slug: 'dumbbell-fly',
    description: 'An isolation exercise that stretches and contracts the chest muscles for definition and shape.',
    category: 'Chest',
    muscleGroups: ['Chest', 'Shoulders'],
    equipment: 'Dumbbell',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    instructions: [
      'Lie on a flat bench holding a dumbbell in each hand above your chest.',
      'Keep a slight bend in your elbows throughout the movement.',
      'Lower the dumbbells out to the sides in a wide arc.',
      'Stop when you feel a stretch in your chest.',
      'Squeeze your chest to bring the dumbbells back together.',
    ],
    tips: [
      'Use lighter weight than pressing exercises.',
      'Focus on the stretch and squeeze of the chest.',
      'Keep the slight bend in elbows — do not straighten arms.',
    ],
    mistakes: [
      'Using too heavy weight — this is an isolation exercise.',
      'Straightening arms — puts stress on elbow joint.',
      'Going too low — can strain the shoulder.',
    ],
    benefits: [
      'Isolates the chest muscles for better definition.',
      'Great stretch at the bottom for muscle growth.',
      'Improves chest flexibility.',
    ],
    contraindications: [
      'Shoulder instability.',
      'Elbow tendonitis.',
    ],
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400',
    video: '',
    caloriesPerMinute: 6,
    defaultSets: 3,
    defaultReps: 12,
    defaultDuration: 0,
    restTime: 60,
  },

  {
    name: 'Incline Bench Press',
    slug: 'incline-bench-press',
    description: 'Targets the upper chest by pressing at an incline angle. Builds a fuller, more balanced chest.',
    category: 'Chest',
    muscleGroups: ['Chest', 'Shoulders', 'Triceps'],
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    instructions: [
      'Set the bench to a 30-45 degree incline.',
      'Lie back and grip the bar slightly wider than shoulder-width.',
      'Unrack the bar and hold it above your upper chest.',
      'Lower the bar to your upper chest.',
      'Press back up to the starting position.',
    ],
    tips: [
      'A 30-degree angle targets upper chest best.',
      'Keep your back against the bench.',
      'Control the weight — do not bounce.',
    ],
    mistakes: [
      'Setting the incline too steep — turns it into a shoulder press.',
      'Arching the back excessively.',
      'Flaring elbows out too wide.',
    ],
    benefits: [
      'Builds the upper chest for a fuller look.',
      'Strengthens the front shoulders.',
      'Balances chest development.',
    ],
    contraindications: [
      'Shoulder impingement.',
      'Lower back issues.',
    ],
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    video: '',
    caloriesPerMinute: 8,
    defaultSets: 4,
    defaultReps: 10,
    defaultDuration: 0,
    restTime: 90,
  },

  // ═══════════════════════════════════════════════════════════════════
  // BACK EXERCISES
  // ═══════════════════════════════════════════════════════════════════

  {
    name: 'Pull-Up',
    slug: 'pull-up',
    description: 'The ultimate upper body pulling exercise. Builds a wide, strong back using your own body weight.',
    category: 'Back',
    muscleGroups: ['Back', 'Biceps', 'Shoulders', 'Core'],
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    instructions: [
      'Hang from a pull-up bar with an overhand grip, hands wider than shoulders.',
      'Engage your back muscles and pull your chin above the bar.',
      'Squeeze your back at the top of the movement.',
      'Lower yourself slowly back to a full hang.',
      'Repeat without swinging or kipping.',
    ],
    tips: [
      'Initiate the pull with your back, not your arms.',
      'Keep your core tight to prevent swinging.',
      'If you cannot do a full pull-up, start with negatives.',
    ],
    mistakes: [
      'Using momentum to swing up.',
      'Not going to full extension at the bottom.',
      'Pulling with arms instead of back.',
    ],
    benefits: [
      'Builds a wide, V-shaped back.',
      'Strengthens grip and forearm muscles.',
      'Functional pulling strength.',
    ],
    contraindications: [
      'Shoulder injuries.',
      'Elbow tendonitis.',
    ],
    image: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400',
    video: '',
    caloriesPerMinute: 8,
    defaultSets: 3,
    defaultReps: 8,
    defaultDuration: 0,
    restTime: 90,
  },

  {
    name: 'Bent-Over Row',
    slug: 'bent-over-row',
    description: 'A fundamental back exercise that builds thickness in the upper and middle back.',
    category: 'Back',
    muscleGroups: ['Back', 'Biceps', 'Shoulders'],
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    instructions: [
      'Stand with feet shoulder-width apart, holding a barbell.',
      'Bend at the hips until your torso is roughly 45 degrees.',
      'Let the barbell hang at arm length below your chest.',
      'Pull the barbell up to your lower chest.',
      'Lower it back down slowly and repeat.',
    ],
    tips: [
      'Keep your back flat — do not round it.',
      'Squeeze your shoulder blades together at the top.',
      'Keep elbows close to your body.',
    ],
    mistakes: [
      'Rounding the lower back — very dangerous.',
      'Using too much momentum.',
      'Standing too upright — reduces back activation.',
    ],
    benefits: [
      'Builds overall back thickness.',
      'Strengthens the posterior chain.',
      'Improves posture.',
    ],
    contraindications: [
      'Lower back injuries.',
      'Herniated disc.',
    ],
    image: 'https://images.unsplash.com/photo-1534368959876-26bf04f2c947?w=400',
    video: '',
    caloriesPerMinute: 7,
    defaultSets: 4,
    defaultReps: 10,
    defaultDuration: 0,
    restTime: 90,
  },

  {
    name: 'Deadlift',
    slug: 'deadlift',
    description: 'The ultimate full-body strength exercise. Picks heavy weight off the floor to build total body power.',
    category: 'Back',
    muscleGroups: ['Back', 'Glutes', 'Hamstrings', 'Core', 'Forearms'],
    equipment: 'Barbell',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    instructions: [
      'Stand with feet hip-width apart, bar over mid-foot.',
      'Bend at hips and knees to grip the bar just outside your legs.',
      'Keep your back flat, chest up, and shoulders back.',
      'Drive through your heels to stand up with the bar.',
      'Lock out at the top, then lower the bar back down.',
    ],
    tips: [
      'Keep the bar close to your body throughout.',
      'Push the floor away rather than pulling the bar up.',
      'Start with lighter weight to learn the form.',
    ],
    mistakes: [
      'Rounding the back — risk of serious injury.',
      'Jerking the bar off the floor.',
      'Letting the bar drift away from the body.',
    ],
    benefits: [
      'Builds total body strength.',
      'Works more muscles than any other single exercise.',
      'Increases grip strength.',
    ],
    contraindications: [
      'Back injuries or herniated disc.',
      'Acute lower back pain.',
    ],
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400',
    video: '',
    caloriesPerMinute: 10,
    defaultSets: 3,
    defaultReps: 5,
    defaultDuration: 0,
    restTime: 120,
  },

  {
    name: 'Lat Pulldown',
    slug: 'lat-pulldown',
    description: 'A machine-based exercise that targets the latissimus dorsi for a wider back. Great for beginners.',
    category: 'Back',
    muscleGroups: ['Back', 'Biceps'],
    equipment: 'Machine',
    difficulty: 'Beginner',
    exerciseType: 'Strength',
    instructions: [
      'Sit at a lat pulldown machine and adjust the thigh pad.',
      'Grab the wide bar with an overhand grip.',
      'Lean back slightly and pull the bar down to your upper chest.',
      'Squeeze your back muscles at the bottom.',
      'Slowly return the bar to the starting position.',
    ],
    tips: [
      'Pull with your elbows, not your hands.',
      'Lean back just slightly — about 10-15 degrees.',
      'Use a full range of motion.',
    ],
    mistakes: [
      'Pulling the bar behind the neck — bad for shoulders.',
      'Leaning back too far — turns it into a row.',
      'Using momentum instead of muscle.',
    ],
    benefits: [
      'Builds a wider back.',
      'Easier to learn than pull-ups.',
      'Adjustable weight for all fitness levels.',
    ],
    contraindications: [
      'Shoulder injuries.',
    ],
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
    video: '',
    caloriesPerMinute: 6,
    defaultSets: 3,
    defaultReps: 12,
    defaultDuration: 0,
    restTime: 60,
  },

  // ═══════════════════════════════════════════════════════════════════
  // SHOULDER EXERCISES
  // ═══════════════════════════════════════════════════════════════════

  {
    name: 'Overhead Press',
    slug: 'overhead-press',
    description: 'A compound pressing movement that builds strong, broad shoulders. Also known as the military press.',
    category: 'Shoulders',
    muscleGroups: ['Shoulders', 'Triceps', 'Core'],
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    instructions: [
      'Stand with feet shoulder-width apart, bar at shoulder height.',
      'Grip the bar just outside shoulder-width.',
      'Press the bar overhead until arms are fully extended.',
      'Lower the bar back to shoulder height.',
      'Keep your core tight throughout.',
    ],
    tips: [
      'Squeeze your glutes for stability.',
      'Push your head through as the bar passes your face.',
      'Do not use leg drive — keep it strict.',
    ],
    mistakes: [
      'Arching the back excessively.',
      'Using leg drive to push the weight.',
      'Not locking out at the top.',
    ],
    benefits: [
      'Builds shoulder strength and size.',
      'Improves overhead stability.',
      'Strengthens the core.',
    ],
    contraindications: [
      'Shoulder impingement.',
      'Lower back issues.',
    ],
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    video: '',
    caloriesPerMinute: 7,
    defaultSets: 4,
    defaultReps: 8,
    defaultDuration: 0,
    restTime: 90,
  },

  {
    name: 'Lateral Raise',
    slug: 'lateral-raise',
    description: 'An isolation exercise that targets the side delts for wider-looking shoulders.',
    category: 'Shoulders',
    muscleGroups: ['Shoulders'],
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    exerciseType: 'Strength',
    instructions: [
      'Stand with a dumbbell in each hand at your sides.',
      'Keep a slight bend in your elbows.',
      'Raise your arms out to the sides until parallel with the floor.',
      'Hold briefly at the top.',
      'Lower slowly back to the starting position.',
    ],
    tips: [
      'Use lighter weight — this is an isolation exercise.',
      'Lead with your elbows, not your hands.',
      'Control the weight on the way down.',
    ],
    mistakes: [
      'Swinging the weights with momentum.',
      'Raising too high — above shoulder level.',
      'Shrugging shoulders up during the lift.',
    ],
    benefits: [
      'Builds wider-looking shoulders.',
      'Isolates the side deltoid.',
      'Improves shoulder stability.',
    ],
    contraindications: [
      'Shoulder impingement.',
      'Rotator cuff injuries.',
    ],
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400',
    video: '',
    caloriesPerMinute: 5,
    defaultSets: 3,
    defaultReps: 15,
    defaultDuration: 0,
    restTime: 45,
  },

  {
    name: 'Face Pull',
    slug: 'face-pull',
    description: 'A cable exercise that strengthens the rear delts and rotator cuff. Essential for shoulder health.',
    category: 'Shoulders',
    muscleGroups: ['Shoulders', 'Back'],
    equipment: 'Cable',
    difficulty: 'Beginner',
    exerciseType: 'Strength',
    instructions: [
      'Set a cable machine to upper chest height with a rope attachment.',
      'Grab the rope with both hands, palms facing each other.',
      'Step back until arms are fully extended.',
      'Pull the rope towards your face, separating the ends.',
      'Squeeze your rear delts, then slowly return.',
    ],
    tips: [
      'Pull to the level of your ears, not your chest.',
      'Keep your elbows high throughout.',
      'Use lighter weight and focus on the squeeze.',
    ],
    mistakes: [
      'Using too much weight.',
      'Pulling too low — should come to face level.',
      'Not separating the rope at the end.',
    ],
    benefits: [
      'Strengthens rear delts and rotator cuff.',
      'Prevents shoulder injuries.',
      'Improves posture.',
    ],
    contraindications: [
      'Acute shoulder pain.',
    ],
    image: 'https://images.unsplash.com/photo-1534368959876-26bf04f2c947?w=400',
    video: '',
    caloriesPerMinute: 4,
    defaultSets: 3,
    defaultReps: 15,
    defaultDuration: 0,
    restTime: 45,
  },

  // ═══════════════════════════════════════════════════════════════════
  // BICEPS EXERCISES
  // ═══════════════════════════════════════════════════════════════════

  {
    name: 'Bicep Curl',
    slug: 'bicep-curl',
    description: 'The classic arm exercise. Isolates the biceps for bigger, stronger arms.',
    category: 'Biceps',
    muscleGroups: ['Biceps', 'Forearms'],
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    exerciseType: 'Strength',
    instructions: [
      'Stand holding a dumbbell in each hand at your sides, palms facing forward.',
      'Keep your elbows close to your body.',
      'Curl the weights up by bending your elbows.',
      'Squeeze your biceps at the top.',
      'Lower the weights slowly back down.',
    ],
    tips: [
      'Do not swing your body to lift the weight.',
      'Keep your upper arms stationary.',
      'Fully extend at the bottom for a complete rep.',
    ],
    mistakes: [
      'Swinging the body for momentum.',
      'Moving elbows forward during the curl.',
      'Not using full range of motion.',
    ],
    benefits: [
      'Builds bicep size and peak.',
      'Improves arm strength.',
      'Simple and effective.',
    ],
    contraindications: [
      'Elbow tendonitis.',
      'Wrist pain.',
    ],
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400',
    video: '',
    caloriesPerMinute: 5,
    defaultSets: 3,
    defaultReps: 12,
    defaultDuration: 0,
    restTime: 60,
  },

  {
    name: 'Hammer Curl',
    slug: 'hammer-curl',
    description: 'A curl variation with neutral grip that targets the brachialis and forearms for thicker arms.',
    category: 'Biceps',
    muscleGroups: ['Biceps', 'Forearms'],
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    exerciseType: 'Strength',
    instructions: [
      'Stand holding dumbbells with palms facing your body (neutral grip).',
      'Keep elbows close to your sides.',
      'Curl the weights up while keeping palms facing each other.',
      'Squeeze at the top of the movement.',
      'Lower slowly back to the starting position.',
    ],
    tips: [
      'Keep your wrists straight throughout.',
      'You can curl both arms together or alternate.',
      'Focus on the squeeze at the top.',
    ],
    mistakes: [
      'Rotating the wrists during the curl.',
      'Using momentum to swing the weight.',
      'Not controlling the negative portion.',
    ],
    benefits: [
      'Targets the brachialis for arm thickness.',
      'Strengthens the forearms.',
      'Easier on the wrists than regular curls.',
    ],
    contraindications: [
      'Elbow pain.',
    ],
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    video: '',
    caloriesPerMinute: 5,
    defaultSets: 3,
    defaultReps: 12,
    defaultDuration: 0,
    restTime: 60,
  },

  // ═══════════════════════════════════════════════════════════════════
  // TRICEPS EXERCISES
  // ═══════════════════════════════════════════════════════════════════

  {
    name: 'Tricep Dip',
    slug: 'tricep-dip',
    description: 'A bodyweight exercise that isolates the triceps. Can be done on parallel bars or a bench.',
    category: 'Triceps',
    muscleGroups: ['Triceps', 'Chest', 'Shoulders'],
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    instructions: [
      'Grip the parallel bars and lift yourself up with straight arms.',
      'Keep your body upright (leaning forward targets chest more).',
      'Lower yourself by bending your elbows to about 90 degrees.',
      'Push back up to the starting position.',
      'Keep elbows close to your body for tricep focus.',
    ],
    tips: [
      'Stay upright to focus on triceps.',
      'Do not go too deep — 90 degrees is enough.',
      'Use a bench for an easier version.',
    ],
    mistakes: [
      'Going too deep — strains the shoulders.',
      'Flaring elbows out — should stay close.',
      'Leaning too far forward — shifts to chest.',
    ],
    benefits: [
      'Builds tricep strength and size.',
      'Bodyweight exercise — no equipment needed.',
      'Also works chest and shoulders.',
    ],
    contraindications: [
      'Shoulder injuries.',
      'Elbow problems.',
    ],
    image: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400',
    video: '',
    caloriesPerMinute: 7,
    defaultSets: 3,
    defaultReps: 10,
    defaultDuration: 0,
    restTime: 60,
  },

  {
    name: 'Tricep Pushdown',
    slug: 'tricep-pushdown',
    description: 'A cable exercise that isolates the triceps. Great for building arm definition.',
    category: 'Triceps',
    muscleGroups: ['Triceps'],
    equipment: 'Cable',
    difficulty: 'Beginner',
    exerciseType: 'Strength',
    instructions: [
      'Stand facing a cable machine with a straight bar or rope attachment.',
      'Grip the attachment with both hands, elbows at your sides.',
      'Push the bar down by straightening your arms.',
      'Squeeze your triceps at the bottom.',
      'Slowly let the bar come back up to the starting position.',
    ],
    tips: [
      'Keep your elbows pinned to your sides.',
      'Only move your forearms — upper arms stay still.',
      'Use a rope attachment for extra tricep squeeze.',
    ],
    mistakes: [
      'Letting elbows drift forward.',
      'Using body weight to push down.',
      'Not fully extending at the bottom.',
    ],
    benefits: [
      'Isolates the triceps effectively.',
      'Easy to learn and perform.',
      'Good for muscle definition.',
    ],
    contraindications: [
      'Elbow tendonitis.',
    ],
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
    video: '',
    caloriesPerMinute: 4,
    defaultSets: 3,
    defaultReps: 15,
    defaultDuration: 0,
    restTime: 45,
  },

  // ═══════════════════════════════════════════════════════════════════
  // LEG EXERCISES
  // ═══════════════════════════════════════════════════════════════════

  {
    name: 'Barbell Squat',
    slug: 'barbell-squat',
    description: 'The king of leg exercises. Builds overall lower body strength, size, and functional power.',
    category: 'Legs',
    muscleGroups: ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    instructions: [
      'Position the barbell on your upper back (not your neck).',
      'Stand with feet shoulder-width apart, toes slightly out.',
      'Bend your knees and hips to lower yourself down.',
      'Go down until your thighs are parallel to the floor.',
      'Push through your heels to stand back up.',
    ],
    tips: [
      'Keep your chest up and back straight.',
      'Push your knees out over your toes.',
      'Go as deep as your mobility allows.',
    ],
    mistakes: [
      'Letting knees cave inward.',
      'Rounding the lower back.',
      'Rising on toes instead of pushing through heels.',
    ],
    benefits: [
      'Builds overall leg strength and size.',
      'Boosts testosterone and growth hormone.',
      'Functional movement for daily life.',
    ],
    contraindications: [
      'Knee injuries.',
      'Lower back problems.',
    ],
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400',
    video: '',
    caloriesPerMinute: 9,
    defaultSets: 4,
    defaultReps: 8,
    defaultDuration: 0,
    restTime: 120,
  },

  {
    name: 'Lunges',
    slug: 'lunges',
    description: 'A unilateral leg exercise that builds balance, strength, and stability one leg at a time.',
    category: 'Legs',
    muscleGroups: ['Quadriceps', 'Glutes', 'Hamstrings'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Strength',
    instructions: [
      'Stand tall with feet hip-width apart.',
      'Step forward with one leg.',
      'Lower your body until both knees are at 90 degrees.',
      'Your back knee should almost touch the floor.',
      'Push through your front heel to return to standing.',
    ],
    tips: [
      'Keep your torso upright throughout.',
      'Take a big enough step so your knee does not pass your toes.',
      'Alternate legs or do all reps on one leg first.',
    ],
    mistakes: [
      'Letting the front knee go past the toes.',
      'Leaning forward too much.',
      'Taking too short of a step.',
    ],
    benefits: [
      'Builds single-leg strength and balance.',
      'Corrects muscle imbalances.',
      'No equipment needed.',
    ],
    contraindications: [
      'Knee injuries.',
      'Balance problems.',
    ],
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    video: '',
    caloriesPerMinute: 7,
    defaultSets: 3,
    defaultReps: 12,
    defaultDuration: 0,
    restTime: 60,
  },

  {
    name: 'Leg Press',
    slug: 'leg-press',
    description: 'A machine exercise that builds quad and glute strength without loading the spine.',
    category: 'Legs',
    muscleGroups: ['Quadriceps', 'Glutes', 'Hamstrings'],
    equipment: 'Machine',
    difficulty: 'Beginner',
    exerciseType: 'Strength',
    instructions: [
      'Sit in the leg press machine with your back flat against the pad.',
      'Place feet shoulder-width apart on the platform.',
      'Release the safety locks.',
      'Lower the platform by bending your knees to about 90 degrees.',
      'Push the platform back up without locking your knees.',
    ],
    tips: [
      'Do not lock your knees at the top.',
      'Keep your lower back pressed against the pad.',
      'Adjust foot position to target different muscles.',
    ],
    mistakes: [
      'Locking out knees at the top — dangerous.',
      'Lifting hips off the pad.',
      'Going too heavy with poor form.',
    ],
    benefits: [
      'Builds leg strength safely.',
      'No spinal loading — good for those with back issues.',
      'Easy to learn and use.',
    ],
    contraindications: [
      'Severe knee injuries.',
    ],
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
    video: '',
    caloriesPerMinute: 7,
    defaultSets: 4,
    defaultReps: 12,
    defaultDuration: 0,
    restTime: 90,
  },

  {
    name: 'Calf Raise',
    slug: 'calf-raise',
    description: 'Isolates the calf muscles for lower leg strength and definition.',
    category: 'Legs',
    muscleGroups: ['Calves'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Strength',
    instructions: [
      'Stand on the edge of a step with heels hanging off.',
      'Rise up on your toes as high as possible.',
      'Squeeze your calves at the top.',
      'Lower your heels below the step for a full stretch.',
      'Repeat for the desired number of reps.',
    ],
    tips: [
      'Use a wall for balance if needed.',
      'Go slow — calves respond to time under tension.',
      'Pause at the top for 1-2 seconds.',
    ],
    mistakes: [
      'Bouncing at the bottom.',
      'Not using full range of motion.',
      'Going too fast.',
    ],
    benefits: [
      'Builds calf strength and size.',
      'Improves ankle stability.',
      'Can be done anywhere.',
    ],
    contraindications: [
      'Achilles tendon injuries.',
      'Ankle sprains.',
    ],
    image: 'https://images.unsplash.com/photo-1534368959876-26bf04f2c947?w=400',
    video: '',
    caloriesPerMinute: 4,
    defaultSets: 4,
    defaultReps: 15,
    defaultDuration: 0,
    restTime: 45,
  },

  // ═══════════════════════════════════════════════════════════════════
  // GLUTE EXERCISES
  // ═══════════════════════════════════════════════════════════════════

  {
    name: 'Hip Thrust',
    slug: 'hip-thrust',
    description: 'The best exercise for glute activation and growth. Builds strong, powerful glutes.',
    category: 'Glutes',
    muscleGroups: ['Glutes', 'Hamstrings', 'Core'],
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    instructions: [
      'Sit on the floor with your upper back against a bench.',
      'Roll a barbell over your hips (use a pad for comfort).',
      'Plant your feet flat on the floor, hip-width apart.',
      'Drive your hips up by squeezing your glutes.',
      'At the top, your body should form a straight line from shoulders to knees.',
    ],
    tips: [
      'Squeeze glutes hard at the top.',
      'Keep your chin tucked slightly.',
      'Drive through your heels.',
    ],
    mistakes: [
      'Hyperextending the lower back at the top.',
      'Placing feet too far away.',
      'Not squeezing glutes enough.',
    ],
    benefits: [
      'Best exercise for glute growth.',
      'Improves hip extension power.',
      'Helps with running and jumping performance.',
    ],
    contraindications: [
      'Lower back pain.',
      'Hip flexor strain.',
    ],
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400',
    video: '',
    caloriesPerMinute: 7,
    defaultSets: 4,
    defaultReps: 12,
    defaultDuration: 0,
    restTime: 60,
  },

  {
    name: 'Glute Bridge',
    slug: 'glute-bridge',
    description: 'A beginner-friendly bodyweight exercise that activates and strengthens the glutes.',
    category: 'Glutes',
    muscleGroups: ['Glutes', 'Hamstrings', 'Core'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Strength',
    instructions: [
      'Lie on your back with knees bent, feet flat on the floor.',
      'Keep your arms at your sides, palms down.',
      'Push through your heels to lift your hips off the floor.',
      'Squeeze your glutes at the top.',
      'Lower your hips back down slowly.',
    ],
    tips: [
      'Keep your core engaged throughout.',
      'Do not push through your toes — use heels.',
      'Hold the top position for 2-3 seconds.',
    ],
    mistakes: [
      'Pushing through toes instead of heels.',
      'Arching the back at the top.',
      'Not squeezing glutes at the top.',
    ],
    benefits: [
      'Great for glute activation.',
      'No equipment needed.',
      'Good warm-up exercise.',
    ],
    contraindications: [
      'Acute lower back pain.',
    ],
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
    video: '',
    caloriesPerMinute: 5,
    defaultSets: 3,
    defaultReps: 15,
    defaultDuration: 0,
    restTime: 45,
  },

  // ═══════════════════════════════════════════════════════════════════
  // CORE EXERCISES
  // ═══════════════════════════════════════════════════════════════════

  {
    name: 'Plank',
    slug: 'plank',
    description: 'An isometric core exercise that builds endurance and stability in the entire midsection.',
    category: 'Core',
    muscleGroups: ['Core', 'Shoulders', 'Back'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Strength',
    instructions: [
      'Get into a push-up position on your forearms.',
      'Keep your body in a straight line from head to heels.',
      'Engage your core by pulling your belly button in.',
      'Hold this position for the desired time.',
      'Do not let your hips sag or pike up.',
    ],
    tips: [
      'Start with 20-30 seconds and work up.',
      'Breathe normally — do not hold your breath.',
      'Look at the floor to keep your neck neutral.',
    ],
    mistakes: [
      'Letting hips sag towards the floor.',
      'Piking hips up too high.',
      'Holding breath.',
    ],
    benefits: [
      'Builds core stability and endurance.',
      'Improves posture.',
      'No equipment needed.',
    ],
    contraindications: [
      'Shoulder injuries.',
      'Lower back pain.',
    ],
    image: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400',
    video: '',
    caloriesPerMinute: 5,
    defaultSets: 3,
    defaultReps: 1,
    defaultDuration: 30,
    restTime: 45,
  },

  {
    name: 'Crunches',
    slug: 'crunches',
    description: 'A basic abdominal exercise that targets the upper abs through spinal flexion.',
    category: 'Core',
    muscleGroups: ['Core'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Strength',
    instructions: [
      'Lie on your back with knees bent, feet flat on the floor.',
      'Place your hands behind your head or across your chest.',
      'Curl your shoulders up off the floor by contracting your abs.',
      'Lift just your shoulder blades — not your whole back.',
      'Lower back down slowly and repeat.',
    ],
    tips: [
      'Do not pull on your neck with your hands.',
      'Exhale as you crunch up.',
      'Focus on squeezing the abs.',
    ],
    mistakes: [
      'Pulling on the neck.',
      'Using momentum to sit all the way up.',
      'Going too fast.',
    ],
    benefits: [
      'Targets the upper abdominals.',
      'Simple and easy to learn.',
      'No equipment needed.',
    ],
    contraindications: [
      'Neck injuries.',
      'Lower back issues.',
    ],
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
    video: '',
    caloriesPerMinute: 5,
    defaultSets: 3,
    defaultReps: 20,
    defaultDuration: 0,
    restTime: 45,
  },

  {
    name: 'Russian Twist',
    slug: 'russian-twist',
    description: 'A rotational core exercise that targets the obliques for a defined waistline.',
    category: 'Core',
    muscleGroups: ['Core', 'Obliques'],
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    instructions: [
      'Sit on the floor with knees bent, feet slightly off the ground.',
      'Lean back slightly to engage your core.',
      'Hold your hands together in front of your chest.',
      'Rotate your torso to the right, then to the left.',
      'Each rotation to one side counts as one rep.',
    ],
    tips: [
      'Keep your back straight — do not round it.',
      'Move slowly and controlled.',
      'Hold a weight for extra challenge.',
    ],
    mistakes: [
      'Rounding the back.',
      'Moving too fast without control.',
      'Not rotating enough — just moving arms.',
    ],
    benefits: [
      'Targets the oblique muscles.',
      'Improves rotational strength.',
      'Builds core stability.',
    ],
    contraindications: [
      'Lower back injuries.',
      'Disc problems.',
    ],
    image: 'https://images.unsplash.com/photo-1534368959876-26bf04f2c947?w=400',
    video: '',
    caloriesPerMinute: 6,
    defaultSets: 3,
    defaultReps: 20,
    defaultDuration: 0,
    restTime: 45,
  },

  {
    name: 'Mountain Climbers',
    slug: 'mountain-climbers',
    description: 'A dynamic core exercise that also provides cardio. Drives your heart rate up while building abs.',
    category: 'Core',
    muscleGroups: ['Core', 'Shoulders', 'Hip Flexors'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Cardio',
    instructions: [
      'Start in a high plank position with arms straight.',
      'Drive your right knee towards your chest.',
      'Quickly switch, bringing your left knee forward.',
      'Continue alternating legs at a running pace.',
      'Keep your hips level and core tight.',
    ],
    tips: [
      'Start slow and increase speed as you warm up.',
      'Keep your shoulders over your wrists.',
      'Breathe rhythmically.',
    ],
    mistakes: [
      'Letting hips bounce up and down.',
      'Not bringing knees far enough forward.',
      'Holding breath.',
    ],
    benefits: [
      'Combines core work with cardio.',
      'Burns lots of calories.',
      'No equipment needed.',
    ],
    contraindications: [
      'Wrist injuries.',
      'Shoulder problems.',
    ],
    image: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400',
    video: '',
    caloriesPerMinute: 10,
    defaultSets: 3,
    defaultReps: 20,
    defaultDuration: 0,
    restTime: 45,
  },

  // ═══════════════════════════════════════════════════════════════════
  // CARDIO EXERCISES
  // ═══════════════════════════════════════════════════════════════════

  {
    name: 'Jumping Jacks',
    slug: 'jumping-jacks',
    description: 'A classic cardio exercise that raises your heart rate and works your whole body.',
    category: 'Cardio',
    muscleGroups: ['Full Body', 'Calves', 'Shoulders'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Cardio',
    instructions: [
      'Stand with feet together and arms at your sides.',
      'Jump and spread your feet wider than hip-width.',
      'At the same time, raise your arms above your head.',
      'Jump back to the starting position.',
      'Repeat at a steady pace.',
    ],
    tips: [
      'Land softly on the balls of your feet.',
      'Keep a steady rhythm.',
      'Great for warming up before a workout.',
    ],
    mistakes: [
      'Landing hard on flat feet.',
      'Not fully extending arms overhead.',
      'Going too fast and losing form.',
    ],
    benefits: [
      'Raises heart rate quickly.',
      'Full body movement.',
      'Great warm-up exercise.',
    ],
    contraindications: [
      'Knee injuries.',
      'Ankle problems.',
    ],
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400',
    video: '',
    caloriesPerMinute: 8,
    defaultSets: 3,
    defaultReps: 30,
    defaultDuration: 0,
    restTime: 30,
  },

  {
    name: 'Burpees',
    slug: 'burpees',
    description: 'The ultimate full-body cardio exercise. Combines a squat, push-up, and jump for maximum calorie burn.',
    category: 'Cardio',
    muscleGroups: ['Full Body', 'Chest', 'Core', 'Legs'],
    equipment: 'Bodyweight',
    difficulty: 'Advanced',
    exerciseType: 'Cardio',
    instructions: [
      'Stand with feet shoulder-width apart.',
      'Drop into a squat and place your hands on the floor.',
      'Jump your feet back into a plank position.',
      'Do a push-up.',
      'Jump your feet forward and explosively jump up with arms overhead.',
    ],
    tips: [
      'Land softly when jumping.',
      'Modify by removing the push-up if needed.',
      'Keep your core tight in the plank.',
    ],
    mistakes: [
      'Not doing a full push-up.',
      'Landing with stiff legs.',
      'Letting form break down when tired.',
    ],
    benefits: [
      'Burns massive calories.',
      'Works every muscle in the body.',
      'Improves cardiovascular fitness.',
    ],
    contraindications: [
      'Wrist injuries.',
      'Knee problems.',
      'Heart conditions.',
    ],
    image: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400',
    video: '',
    caloriesPerMinute: 12,
    defaultSets: 3,
    defaultReps: 10,
    defaultDuration: 0,
    restTime: 60,
  },

  {
    name: 'High Knees',
    slug: 'high-knees',
    description: 'A running-in-place cardio exercise that fires up your core and hip flexors.',
    category: 'Cardio',
    muscleGroups: ['Core', 'Hip Flexors', 'Calves'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    exerciseType: 'Cardio',
    instructions: [
      'Stand with feet hip-width apart.',
      'Run in place, driving your knees up to waist height.',
      'Pump your arms as if sprinting.',
      'Land on the balls of your feet.',
      'Maintain a fast pace.',
    ],
    tips: [
      'Aim to get your knees to hip height.',
      'Stay on the balls of your feet.',
      'Use your arms for momentum.',
    ],
    mistakes: [
      'Knees not coming up high enough.',
      'Leaning back too far.',
      'Flat-footed landing.',
    ],
    benefits: [
      'Great cardio workout.',
      'Strengthens hip flexors.',
      'Improves coordination.',
    ],
    contraindications: [
      'Knee injuries.',
      'Hip flexor strain.',
    ],
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    video: '',
    caloriesPerMinute: 9,
    defaultSets: 3,
    defaultReps: 20,
    defaultDuration: 0,
    restTime: 30,
  },

  // ═══════════════════════════════════════════════════════════════════
  // FULL BODY EXERCISES
  // ═══════════════════════════════════════════════════════════════════

  {
    name: 'Kettlebell Swing',
    slug: 'kettlebell-swing',
    description: 'A explosive hip-hinge exercise that builds power in the glutes, hamstrings, and core.',
    category: 'Full Body',
    muscleGroups: ['Glutes', 'Hamstrings', 'Core', 'Shoulders'],
    equipment: 'Kettlebell',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    instructions: [
      'Stand with feet wider than shoulder-width, kettlebell on the floor.',
      'Hinge at your hips and grab the kettlebell with both hands.',
      'Hike the kettlebell back between your legs.',
      'Drive your hips forward to swing the kettlebell up to chest height.',
      'Let gravity bring it back down and hike it between your legs again.',
    ],
    tips: [
      'This is a hip exercise, not a squat or arm lift.',
      'Snap your hips at the top.',
      'Keep your arms relaxed — they are just holding the weight.',
    ],
    mistakes: [
      'Using arms to lift the kettlebell.',
      'Squatting instead of hinging.',
      'Rounding the back.',
    ],
    benefits: [
      'Builds explosive hip power.',
      'Great for fat loss and conditioning.',
      'Works the entire posterior chain.',
    ],
    contraindications: [
      'Lower back injuries.',
      'Shoulder problems.',
    ],
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400',
    video: '',
    caloriesPerMinute: 10,
    defaultSets: 3,
    defaultReps: 15,
    defaultDuration: 0,
    restTime: 60,
  },

  {
    name: 'Clean and Press',
    slug: 'clean-and-press',
    description: 'A compound movement that combines a power clean with an overhead press for total body strength.',
    category: 'Full Body',
    muscleGroups: ['Shoulders', 'Legs', 'Back', 'Core', 'Arms'],
    equipment: 'Barbell',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    instructions: [
      'Stand with feet hip-width apart, barbell on the floor.',
      'Clean the barbell to your shoulders in one explosive movement.',
      'Catch the bar at shoulder height in a front rack position.',
      'Press the barbell overhead until arms are fully extended.',
      'Lower back to shoulders, then to the floor.',
    ],
    tips: [
      'Learn the clean and press separately first.',
      'Start with light weight to practice form.',
      'Use your legs to generate power for the clean.',
    ],
    mistakes: [
      'Using arms instead of hips for the clean.',
      'Not catching the bar properly at the shoulders.',
      'Pressing without re-setting between reps.',
    ],
    benefits: [
      'Total body strength and power.',
      'Time-efficient — works everything.',
      'Builds athletic performance.',
    ],
    contraindications: [
      'Shoulder injuries.',
      'Wrist problems.',
      'Lower back issues.',
    ],
    image: 'https://images.unsplash.com/photo-1534368959876-26bf04f2c947?w=400',
    video: '',
    caloriesPerMinute: 11,
    defaultSets: 3,
    defaultReps: 6,
    defaultDuration: 0,
    restTime: 120,
  },

  // ═══════════════════════════════════════════════════════════════════
  // STRETCHING EXERCISES
  // ═══════════════════════════════════════════════════════════════════

  {
    name: 'Hamstring Stretch',
    slug: 'hamstring-stretch',
    description: 'A static stretch that lengthens the hamstrings and relieves tightness in the back of the legs.',
    category: 'Stretching',
    muscleGroups: ['Hamstrings', 'Lower Back'],
    equipment: 'None',
    difficulty: 'Beginner',
    exerciseType: 'Flexibility',
    instructions: [
      'Sit on the floor with one leg extended and the other bent.',
      'Reach forward towards the toes of your extended leg.',
      'Keep your back straight — do not round it.',
      'Hold the stretch for 20-30 seconds.',
      'Switch legs and repeat.',
    ],
    tips: [
      'Do not bounce — hold the stretch steady.',
      'Breathe deeply and relax into it.',
      'You should feel a gentle pull, not pain.',
    ],
    mistakes: [
      'Rounding the back to reach further.',
      'Bouncing to try to go deeper.',
      'Holding breath.',
    ],
    benefits: [
      'Improves hamstring flexibility.',
      'Reduces lower back tightness.',
      'Prevents injuries.',
    ],
    contraindications: [
      'Hamstring tears.',
      'Acute sciatica.',
    ],
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    video: '',
    caloriesPerMinute: 2,
    defaultSets: 2,
    defaultReps: 1,
    defaultDuration: 30,
    restTime: 10,
  },

  {
    name: 'Quad Stretch',
    slug: 'quad-stretch',
    description: 'A standing stretch that targets the quadriceps and hip flexors for improved flexibility.',
    category: 'Stretching',
    muscleGroups: ['Quadriceps', 'Hip Flexors'],
    equipment: 'None',
    difficulty: 'Beginner',
    exerciseType: 'Flexibility',
    instructions: [
      'Stand on one leg (hold a wall for balance if needed).',
      'Bend your other knee and grab your ankle behind you.',
      'Pull your heel towards your glute.',
      'Keep your knees close together.',
      'Hold for 20-30 seconds, then switch legs.',
    ],
    tips: [
      'Keep your standing leg slightly bent.',
      'Push your hip forward for a deeper stretch.',
      'Stand tall — do not lean forward.',
    ],
    mistakes: [
      'Pulling the foot to the side instead of straight back.',
      'Leaning forward.',
      'Locking the standing knee.',
    ],
    benefits: [
      'Improves quad flexibility.',
      'Relieves tight hip flexors.',
      'Good for post-workout recovery.',
    ],
    contraindications: [
      'Knee injuries.',
    ],
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    video: '',
    caloriesPerMinute: 2,
    defaultSets: 2,
    defaultReps: 1,
    defaultDuration: 30,
    restTime: 10,
  },

  // ═══════════════════════════════════════════════════════════════════
  // YOGA EXERCISES
  // ═══════════════════════════════════════════════════════════════════

  {
    name: 'Downward Dog',
    slug: 'downward-dog',
    description: 'A fundamental yoga pose that stretches the hamstrings, calves, and shoulders while building strength.',
    category: 'Yoga',
    muscleGroups: ['Hamstrings', 'Calves', 'Shoulders', 'Core'],
    equipment: 'None',
    difficulty: 'Beginner',
    exerciseType: 'Flexibility',
    instructions: [
      'Start on your hands and knees.',
      'Lift your hips up and back, straightening your legs.',
      'Form an inverted V shape with your body.',
      'Press your heels towards the floor.',
      'Hold for 30-60 seconds while breathing deeply.',
    ],
    tips: [
      'Spread your fingers wide for a stable base.',
      'Pedal your feet to warm up the calves.',
      'It is okay if heels do not touch the floor.',
    ],
    mistakes: [
      'Rounding the back.',
      'Locking the knees.',
      'Holding breath.',
    ],
    benefits: [
      'Stretches the entire back body.',
      'Builds shoulder and arm strength.',
      'Calms the mind.',
    ],
    contraindications: [
      'Carpal tunnel syndrome.',
      'Shoulder injuries.',
      'High blood pressure.',
    ],
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    video: '',
    caloriesPerMinute: 3,
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 45,
    restTime: 15,
  },

  {
    name: 'Warrior Pose',
    slug: 'warrior-pose',
    description: 'A powerful standing yoga pose that builds leg strength, balance, and focus.',
    category: 'Yoga',
    muscleGroups: ['Quadriceps', 'Glutes', 'Core', 'Shoulders'],
    equipment: 'None',
    difficulty: 'Beginner',
    exerciseType: 'Flexibility',
    instructions: [
      'Stand with feet wide apart, about 3-4 feet.',
      'Turn your right foot out 90 degrees.',
      'Bend your right knee to 90 degrees (do not go past your toes).',
      'Extend both arms out to the sides at shoulder height.',
      'Hold and breathe, then switch sides.',
    ],
    tips: [
      'Keep your back leg straight and strong.',
      'Look over your front hand.',
      'Keep your torso centered — do not lean forward.',
    ],
    mistakes: [
      'Letting the front knee cave inward.',
      'Leaning the torso over the front leg.',
      'Dropping the arms.',
    ],
    benefits: [
      'Builds leg strength and endurance.',
      'Improves balance and focus.',
      'Opens the hips and chest.',
    ],
    contraindications: [
      'Knee injuries.',
      'Hip problems.',
    ],
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    video: '',
    caloriesPerMinute: 3,
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 30,
    restTime: 15,
  },

  // ═══════════════════════════════════════════════════════════════════
  // ARMS (GENERAL) EXERCISE
  // ═══════════════════════════════════════════════════════════════════

  {
    name: 'Diamond Push-Up',
    slug: 'diamond-push-up',
    description: 'A push-up variation with hands close together that heavily targets the triceps and inner chest.',
    category: 'Arms',
    muscleGroups: ['Triceps', 'Chest', 'Shoulders'],
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    instructions: [
      'Get into push-up position.',
      'Place your hands close together so thumbs and index fingers form a diamond shape.',
      'Lower your chest towards your hands.',
      'Push back up to the starting position.',
      'Keep your elbows close to your body throughout.',
    ],
    tips: [
      'Keep your core tight and body straight.',
      'Go slow for maximum tricep activation.',
      'If too hard, do them from your knees.',
    ],
    mistakes: [
      'Flaring elbows out wide.',
      'Letting hips sag.',
      'Not going low enough.',
    ],
    benefits: [
      'Excellent tricep builder.',
      'No equipment needed.',
      'Also works inner chest.',
    ],
    contraindications: [
      'Wrist pain.',
      'Shoulder injuries.',
    ],
    image: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400',
    video: '',
    caloriesPerMinute: 8,
    defaultSets: 3,
    defaultReps: 10,
    defaultDuration: 0,
    restTime: 60,
  },
];

// ═══════════════════════════════════════════════════════════════════════
// EXPORT THE SEED DATA
// ═══════════════════════════════════════════════════════════════════════

module.exports = exercises;
